// print("Hello World!")

// moveForward()
// moveForward()
// moveForward()
// collectGem()

// moveForward()
// moveForward()
// turnLeft()
// moveForward()
// moveForward()
// collectGem()

// moveForward()
// moveForward()
// turnLeft()
// moveForward()
// collectGem()
// moveForward()
// turnLeft()
// moveForward()
// moveForward()
// toggleSwitch()

// moveForward()
// moveForward()
// moveForward()
// turnLeft()
// moveForward()
// moveForward()
// toggleSwitch()
// moveForward()
// moveForward()
// turnLeft()
// moveForward()
// moveForward()
// collectGem()
